'use client';

import React, { useState, useRef, useEffect } from 'react';
import {
  MessageSquare,
  Code,
  Copy,
  Check,
  Play,
  Zap,
  Search,
  MoreVertical,
  Terminal,
  Loader2,
  Download,
} from 'lucide-react';
import SyntaxHighlighter from 'react-syntax-highlighter';
import { atomOneDark } from 'react-syntax-highlighter/dist/esm/styles/hljs';
import ReactMarkdown from 'react-markdown';
import { jsPDF } from "jspdf";

// Define message type including the new TIMESTAMP field
type Message = {
  role: string;
  content: string;
  type?: 'general' | 'analysis' | 'optimization';
  isHidden?: boolean;
  timestamp: string; // ✅ New field to fix hydration error
};

// Helper to get current time string
const getCurrentTime = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

export default function ChatbotPage() {
  const [code, setCode] = useState(`print("""
 ██████╗ ██████╗ ██████╗ ███████╗    ██╗     ███████╗███╗   ██╗███████╗
██╔════╝██╔═══██╗██╔══██╗██╔════╝    ██║     ██╔════╝████╗  ██║██╔════╝
██║     ██║   ██║██║  ██║█████╗      ██║     █████╗  ██╔██╗ ██║███████╗
██║     ██║   ██║██║  ██║██╔══╝      ██║     ██╔══╝  ██║╚██╗██║╚════██║
╚██████╗╚██████╔╝██████╔╝███████╗    ███████╗███████╗██║ ╚████║███████║
 ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝    ╚══════╝╚══════╝╚═╝  ╚═══╝╚══════╝
""")

team_name = "Team Kernel"
team_size = 3
print(f"""

Built by: {team_name}
Team Size: {team_size}

Sharper Reviews. Smarter Code.

""")`);

  // Initialize with a static timestamp or current time (client-side only logic handled by useEffect usually, 
  // but for initial state it's safer to use a fixed string or handle hydration carefully. 
  // For simplicity in this hackathon, we initialize with a generic time or wait for mount.)
  // However, simpler fix: just use empty string and update on mount, OR just use getCurrentTime() 
  // but we must ensure this runs on client. 
  // SAFEST FIX: We define the state, but we suppress hydration warning on the timestamp span or use a mounted check.
  // actually, simply defining it here usually works if we don't rely on server-exact matching for the initial state 
  // OR we can just hardcode the welcome message time.
  const [messages, setMessages] = useState<Message[]>([
    { 
      role: 'ai', 
      content: 'Hello There! I am ready to Analyze or Optimize your code.', 
      type: 'general',
      timestamp: 'Now' 
    }
  ]);

  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [mounted, setMounted] = useState(false); // To prevent hydration mismatch on initial render

  const lineNumberRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Ensure we only render dynamic content after mount
  useEffect(() => {
    setMounted(true);
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };
  
  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleScroll = () => {
    if (lineNumberRef.current && textareaRef.current) {
      lineNumberRef.current.scrollTop = textareaRef.current.scrollTop;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleExportPDF = (content: string) => {
    const doc = new jsPDF();
    const pageWidth = 170;
    const margin = 20;
    let y = 45; 

    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185); 
    doc.setFont("helvetica", "bold");
    doc.text("CodeLens Audit Report", margin, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by CodeLens • ${new Date().toLocaleString()}`, margin, 30);
    
    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(margin, 35, 190, 35);

    const cleanContent = content
      .replace(/\*\*/g, "") 
      .replace(/###/g, "")  
      .replace(/`/g, "");   

    const lines = cleanContent.split('\n');

    lines.forEach((line) => {
        doc.setFontSize(11);
        doc.setTextColor(60); 
        doc.setFont("helvetica", "normal");

        const trimmedLine = line.trim();
        const isBullet = trimmedLine.startsWith('*') || trimmedLine.startsWith('-');
        const isHeader = (line.match(/^[A-Z][a-z]+:/) || trimmedLine.endsWith(':')) && trimmedLine.length < 50;

        if (isHeader) {
            y += 5; 
            doc.setTextColor(0, 0, 0); 
            doc.setFont("helvetica", "bold");
            doc.setFontSize(13);
            doc.text(trimmedLine, margin, y);
            y += 8; 

        } else if (isBullet) {
            doc.setTextColor(0, 51, 102); 
            const cleanLine = "•  " + trimmedLine.replace(/^[*|-]/, '').trim();
            const splitLines = doc.splitTextToSize(cleanLine, pageWidth);
            doc.text(splitLines, margin, y);
            y += (splitLines.length * 6) + 2; 

        } else {
            if (trimmedLine.length > 0) {
                const splitLines = doc.splitTextToSize(trimmedLine, pageWidth);
                doc.text(splitLines, margin, y);
                y += (splitLines.length * 5) + 2;
            }
        }

        if (y > 270) {
            doc.addPage();
            y = 20; 
        }
    });

    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Powered by Groq & Team Kernel", margin, 285);

    doc.save("CodeLens-Report.pdf");
  };

  const lineCount = Math.max(code.split('\n').length, 15);

  const callGroqAPI = async (userPrompt: string, messageType: 'general' | 'analysis' | 'optimization' = 'general') => {
    setIsLoading(true);
    
    const newHistory = [...messages];
    const isHidden = messageType !== 'general';
    
    // ✅ Add timestamp here
    newHistory.push({ 
        role: 'user', 
        content: userPrompt, 
        type: 'general', 
        isHidden: isHidden,
        timestamp: getCurrentTime()
    });
    
    setMessages(newHistory);

    try {
      const historyForAI = newHistory.map(m => ({ 
          role: m.role === 'ai' ? 'assistant' : 'user', 
          content: m.content 
      }));

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: userPrompt,
          code: code,
          history: historyForAI
        }),
      });

      const data = await response.json();
      const aiText = data.response;

      const codeBlockRegex = /```(?:[\w]*\n)?([\s\S]*?)```/;
      const match = aiText.match(codeBlockRegex);

      let chatDisplayMessage = aiText;

      if (match && match[1]) {
        const extractedCode = match[1].trim();
        setCode(extractedCode);
        chatDisplayMessage = aiText.replace(codeBlockRegex, '').trim();

        if (!chatDisplayMessage) {
          chatDisplayMessage = "✅ I have optimized the code as requested.";
        }
      }

      // ✅ Add timestamp here too
      setMessages(prev => [...prev, { 
          role: 'ai', 
          content: chatDisplayMessage, 
          type: messageType,
          timestamp: getCurrentTime()
      }]);

    } catch (error) {
      setMessages(prev => [...prev, { 
          role: 'ai', 
          content: "Error connecting to AI. Check API Key.", 
          type: 'general',
          timestamp: getCurrentTime()
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSend = () => {
    if(!input.trim()) return;
    const msg = input;
    setInput('');
    callGroqAPI(msg, 'general');
  };

  const handleAnalyze = () => {
    callGroqAPI("Analyze this code for logic, security, and performance issues. Provide a detailed bullet-point report. DO NOT rewrite the code.", 'analysis');
  };

  const handleOptimize = () => {
    callGroqAPI("Optimize this code for better performance and readability. Return the full updated code block.", 'optimization');
  };

  // Prevent rendering until client is mounted to avoid hydration mismatch
  if (!mounted) return null; 

  return (
    <div className="flex h-screen w-full bg-zinc-950 text-gray-200 font-sans overflow-hidden">
      
      {/* LEFT COLUMN: Code Editor */}
      <div className="flex-1 flex flex-col border-r border-white/5 relative min-h-0">
        
        {/* Header */}
        <div className="h-14 flex-none border-b border-white/5 flex items-center justify-between px-6 bg-zinc-900/40 backdrop-blur-md z-10">
          <div className="flex items-center gap-4">
             <div className="flex items-center gap-2 text-sm text-gray-400 hover:text-white cursor-pointer transition-colors group">
                <Code className="w-4 h-4 group-hover:text-blue-400 transition-colors" />
                <span className="font-medium">script.py</span>
             </div>
             <span className="text-zinc-700">/</span>
             <span className="text-xs text-zinc-500 uppercase tracking-wider font-semibold">Editable</span>
          </div>

          <div className="flex items-center gap-3">
             <button 
               onClick={handleCopy}
               className="flex items-center gap-2 px-3 py-1.5 bg-white/5 hover:bg-white/10 border border-white/5 text-xs text-gray-300 rounded-lg transition-all"
             >
                {isCopied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                {isCopied ? 'Copied!' : 'Copy'}
             </button>

             <button 
                onClick={handleAnalyze}
                disabled={isLoading}
                className="flex items-center gap-2 px-4 py-1.5 bg-blue-600/10 text-blue-400 border border-blue-600/20 text-xs font-bold rounded-lg hover:bg-blue-600/20 transition-all disabled:opacity-50"
             >
                {isLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Search className="w-3 h-3" />}
                Analyze
             </button>

             <button 
                onClick={handleOptimize}
                disabled={isLoading}
                className="flex items-center gap-2 px-4 py-1.5 bg-white text-black text-xs font-bold rounded-lg hover:bg-gray-200 transition-all shadow-[0_0_15px_rgba(255,255,255,0.1)] disabled:opacity-50"
             >
                {isLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Zap className="w-3 h-3 fill-current" />}
                Optimize
             </button>
          </div>
        </div>

        {/* Editor Area */}
        <div className="flex-1 relative group min-h-0 bg-zinc-900/20 overflow-hidden flex flex-col">
          <div className="flex-1 overflow-auto flex relative">
            <div 
              ref={lineNumberRef}
              className="w-12 bg-transparent border-r border-white/5 flex flex-col items-end pt-4 pr-3 text-zinc-600 text-sm font-mono select-none overflow-hidden flex-shrink-0"
            >
               {Array.from({ length: lineCount }).map((_, i) => (
                 <div key={i} className="leading-6 h-6">{i + 1}</div>
               ))}
            </div>

            <div className="flex-1 relative">
              <div className="absolute inset-0 overflow-auto pointer-events-none">
                <SyntaxHighlighter
                  language="python"
                  style={atomOneDark}
                  customStyle={{ backgroundColor: 'transparent', padding: '1rem', margin: 0, fontSize: '0.875rem', lineHeight: '1.5rem', fontFamily: 'monospace' }}
                  showLineNumbers={false}
                >
                  {code}
                </SyntaxHighlighter>
              </div>
              <textarea
                ref={textareaRef}
                onScroll={handleScroll}
                value={code}
                onChange={(e) => setCode(e.target.value)}
                spellCheck="false"
                className="absolute inset-0 w-full h-full bg-transparent text-transparent font-mono text-sm leading-6 p-4 resize-none focus:outline-none placeholder:text-transparent overflow-auto whitespace-pre caret-white"
                placeholder="// Paste your code here..."
                style={{ caretColor: 'white' }} 
              />
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="h-10 flex-none border-t border-white/5 bg-zinc-900/40 backdrop-blur-md flex items-center px-4 gap-6 text-xs text-zinc-500 font-mono">
           <div className="flex items-center gap-2 hover:text-gray-300 cursor-pointer transition-colors">
              <Terminal className="w-3 h-3" />
              <span>Ready</span>
           </div>
           <div className="ml-auto flex items-center gap-3">
              <span>Ln {code.split('\n').length}, Col 1</span>
              <span className="w-px h-3 bg-zinc-700"></span>
              <span>UTF-8</span>
              <span>Python</span>
           </div>
        </div>
      </div>

      {/* RIGHT COLUMN: Chat Interface */}
      <div className="flex flex-col w-[420px] bg-black/20 border-l border-white/5 backdrop-blur-xl">
        
        {/* Chat Header */}
        <div className="p-4 border-b border-white/5 bg-zinc-900/20 backdrop-blur-md flex-none z-10">
          <div className="flex items-center justify-between">
             <div className="flex items-center gap-3">
                 <div className="h-8 w-8 bg-gradient-to-br from-zinc-800 to-black rounded-lg flex items-center justify-center border border-white/10 shadow-sm">
                    <MessageSquare className="w-4 h-4 text-white" />
                 </div>
                 <div>
                    <h2 className="text-sm font-semibold text-white leading-none">AI Assistant</h2>
                    <span className="text-[10px] text-zinc-500 font-medium">CODE LENS AI 3.0 - BY TEAM KERNEL</span>
                 </div>
             </div>
             <button className="text-zinc-500 hover:text-white transition-colors">
                <MoreVertical className="w-4 h-4" />
             </button>
          </div>
        </div>

        {/* Chat Messages */}
        <div className="flex-1 overflow-y-auto p-5 space-y-6 min-h-0 scroll-smooth">
           {messages.filter(m => !m.isHidden).map((msg, idx) => ( 
               <div key={idx} className={`group flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'} animate-in fade-in slide-in-from-bottom-2 duration-300`}>
                   
                   <div className={`max-w-[85%] px-4 py-3 text-sm shadow-lg backdrop-blur-sm rounded-2xl ${
                       msg.role === 'user' 
                       ? 'bg-white text-black rounded-br-sm font-medium' 
                       : 'bg-zinc-800/80 text-gray-200 border border-white/10 rounded-bl-sm'
                   }`}>
                       <ReactMarkdown 
                          components={{
                            strong: ({node, ...props}) => <span className="font-bold text-blue-300" {...props} />,
                            ul: ({node, ...props}) => <ul className="list-disc pl-4 space-y-1" {...props} />,
                            ol: ({node, ...props}) => <ol className="list-decimal pl-4 space-y-1" {...props} />,
                            code: ({node, ...props}) => <code className="bg-black/30 px-1 py-0.5 rounded text-xs font-mono text-yellow-300" {...props} />
                          }}
                       >
                         {msg.content}
                       </ReactMarkdown>
                   </div>
                   
                   {/* Meta Data Row & Action Bar */}
                   <div className="flex items-center gap-2 mt-2 px-1">
                      <span className="text-[10px] text-zinc-500 font-medium tracking-wide">
                        {/* ✅ FIXED: Use the stored timestamp, not new Date() */}
                        {msg.role === 'user' ? 'You' : 'AI'} • {msg.timestamp}
                      </span>
                      
                      {/* ACTION BAR */}
                      {msg.role === 'ai' && (
                        <div className="flex items-center gap-3 ml-2">
                           <button 
                             onClick={() => navigator.clipboard.writeText(msg.content)}
                             className="flex items-center gap-1 text-[10px] text-zinc-400 hover:text-white transition-colors" 
                             title="Copy Text"
                           >
                              <Copy className="w-3 h-3" />
                              <span>Copy</span>
                           </button>

                           {msg.type === 'analysis' && (
                               <button 
                                 onClick={() => handleExportPDF(msg.content)}
                                 className="flex items-center gap-1 text-[10px] text-blue-400 hover:text-blue-300 transition-colors border border-blue-500/30 px-2 py-0.5 rounded-full bg-blue-500/10" 
                                 title="Export Audit Report"
                               >
                                  <Download className="w-3 h-3" />
                                  <span>Export PDF</span>
                               </button>
                           )}
                        </div>
                      )}
                   </div>
               </div>
           ))}
           
           {isLoading && (
             <div className="flex flex-col items-start animate-in fade-in slide-in-from-bottom-2">
               <div className="bg-zinc-800/80 text-gray-200 border border-white/10 rounded-2xl rounded-bl-sm px-4 py-3 flex items-center gap-2">
                 <Loader2 className="w-4 h-4 animate-spin" />
                 <span className="text-sm">Thinking...</span>
               </div>
             </div>
           )}
           <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-6 pt-2 pb-8 bg-gradient-to-t from-black via-black/80 to-transparent flex-none">
          <div className="hover:bg-zinc-900/80 bg-zinc-900/60 group w-full flex items-center gap-4 rounded-full border border-white/10 p-1 pl-4 shadow-xl shadow-black/50 transition-colors duration-300 hover:border-white/20">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSend()}
              placeholder="Ask AI to review or modify..."
              className="flex-1 bg-transparent border-none focus:outline-none text-sm text-white placeholder-zinc-500 font-medium caret-white"
            />
            <span className="block h-4 w-0.5 border-l bg-white/10"></span>
            
            <button 
                onClick={handleSend}
                disabled={isLoading}
                className="bg-white/10 group-hover:bg-white/20 size-6 overflow-hidden rounded-full duration-500 cursor-pointer flex-shrink-0 disabled:opacity-50"
            >
              <div className="flex w-12 -translate-x-1/2 duration-500 ease-in-out group-hover:translate-x-0">
                <span className="flex size-6 items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="m-auto size-3 text-white" aria-hidden="true"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path></svg>
                </span>
                <span className="flex size-6 items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="m-auto size-3 text-white" aria-hidden="true"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path></svg>
                </span>
              </div>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}